
const STUDENTS = [
    {
        studentID:0,
        firstName:"Melinda",
        lastName:"Siebeneicher",
        courses:
            [
                {courseID:11,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:14,"started":{semester:"Autumn",year:2015},passedCredits:1},
                {courseID:0,"started":{semester:"Autumn",year:2019},passedCredits:4},
                {courseID:12,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:9,"started":{semester:"Autumn",year:2015},passedCredits:5},
                {courseID:3,"started":{semester:"Autumn",year:2019},passedCredits:7.5}
            ]
    },

        // Och resten av studenterna
        {studentID:1,firstName:"Tintin",lastName:"Söderqvist",courses:
                [{courseID:13,"started":{semester:"Spring",year:2014},passedCredits:7},
                {courseID:8,"started":{semester:"Autumn",year:2014},passedCredits:4},
                {courseID:6,"started":{semester:"Spring",year:2019},passedCredits:15},
                {courseID:3,"started":{semester:"Autumn",year:2015},passedCredits:7.5},
                {courseID:19,"started":{semester:"Autumn",year:2016},passedCredits:2},
                {courseID:29,"started":{semester:"Spring",year:2017},passedCredits:7.5},
                {courseID:29,"started":{semester:"Spring",year:2014},passedCredits:7.5},
                {courseID:5,"started":{semester:"Autumn",year:2017},passedCredits:15},
                {courseID:19,"started":{semester:"Spring",year:2015},passedCredits:7.5},
                {courseID:4,"started":{semester:"Spring",year:2018},passedCredits:5},
                {courseID:10,"started":{semester:"Autumn",year:2016},passedCredits:13},
                {courseID:3,"started":{semester:"Spring",year:2018},passedCredits:7.5}]},
        {studentID:2,firstName:"Wilma",lastName:"Einarsson",courses:
                [{courseID:21,"started":{semester:"Spring",year:2016},passedCredits:6},
                {courseID:21,"started":{semester:"Autumn",year:2019},passedCredits:7},
                {courseID:0,"started":{semester:"Autumn",year:2017},passedCredits:0},
                {courseID:18,"started":{semester:"Autumn",year:2016},passedCredits:2},
                {courseID:6,"started":{semester:"Spring",year:2015},passedCredits:15},
                {courseID:9,"started":{semester:"Autumn",year:2016},passedCredits:5},
                {courseID:15,"started":{semester:"Autumn",year:2017},passedCredits:2},
                {courseID:8,"started":{semester:"Autumn",year:2018},passedCredits:0},
                {courseID:7,"started":{semester:"Spring",year:2015},passedCredits:15},
                {courseID:28,"started":{semester:"Spring",year:2018},passedCredits:7.5},
                {courseID:2,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:26,"started":{semester:"Spring",year:2018},passedCredits:7.5},
                {courseID:7,"started":{semester:"Spring",year:2015},passedCredits:14},
                {courseID:11,"started":{semester:"Spring",year:2018},passedCredits:5}]},
        {studentID:3,firstName:"Jonna",lastName:"Stark Jönsson",courses:
                [{courseID:29,"started":{semester:"Spring",year:2019},passedCredits:6},
                {courseID:9,"started":{semester:"Autumn",year:2015},passedCredits:5},
                {courseID:22,"started":{semester:"Spring",year:2014},passedCredits:15},
                {courseID:14,"started":{semester:"Autumn",year:2019},passedCredits:0},
                {courseID:13,"started":{semester:"Autumn",year:2017},passedCredits:15},
                {courseID:28,"started":{semester:"Autumn",year:2016},passedCredits:4},
                {courseID:26,"started":{semester:"Spring",year:2015},passedCredits:7.5},
                {courseID:25,"started":{semester:"Autumn",year:2017},passedCredits:2}]},
        {studentID:4,firstName:"Isak",lastName:"Andersson",courses:
                [{courseID:24,"started":{semester:"Autumn",year:2015},passedCredits:9},
                {courseID:29,"started":{semester:"Autumn",year:2014},passedCredits:4},
                {courseID:20,"started":{semester:"Autumn",year:2016},passedCredits:12.5},
                {courseID:17,"started":{semester:"Autumn",year:2014},passedCredits:4},
                {courseID:13,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:20,"started":{semester:"Autumn",year:2015},passedCredits:12.5},
                {courseID:4,"started":{semester:"Spring",year:2015},passedCredits:5},
                {courseID:11,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:21,"started":{semester:"Spring",year:2017},passedCredits:7.5},
                {courseID:16,"started":{semester:"Spring",year:2014},passedCredits:5},
                {courseID:14,"started":{semester:"Autumn",year:2019},passedCredits:5},
                {courseID:4,"started":{semester:"Spring",year:2017},passedCredits:3}]},
        {studentID:5,firstName:"Elsa",lastName:"Söderqvist",courses:
                [{courseID:3,"started":{semester:"Spring",year:2014},passedCredits:7.5},
                {courseID:27,"started":{semester:"Spring",year:2014},passedCredits:12.5},
                {courseID:13,"started":{semester:"Autumn",year:2014},passedCredits:15},
                {courseID:28,"started":{semester:"Spring",year:2018},passedCredits:7},
                {courseID:19,"started":{semester:"Spring",year:2017},passedCredits:7.5},
                {courseID:7,"started":{semester:"Spring",year:2014},passedCredits:1},
                {courseID:10,"started":{semester:"Spring",year:2014},passedCredits:15},
                {courseID:8,"started":{semester:"Spring",year:2014},passedCredits:0},
                {courseID:9,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:29,"started":{semester:"Autumn",year:2017},passedCredits:7.5},
                {courseID:18,"started":{semester:"Autumn",year:2014},passedCredits:4}]},
        {studentID:6,firstName:"Clara Marie",lastName:"Sigeback",courses:
                [{courseID:21,"started":{semester:"Autumn",year:2015},passedCredits:0},
                {courseID:23,"started":{semester:"Autumn",year:2014},passedCredits:1},
                {courseID:0,"started":{semester:"Spring",year:2018},passedCredits:15},
                {courseID:11,"started":{semester:"Autumn",year:2017},passedCredits:5},
                {courseID:6,"started":{semester:"Autumn",year:2014},passedCredits:7},
                {courseID:19,"started":{semester:"Autumn",year:2016},passedCredits:0}]},
        {studentID:7,firstName:"Isak",lastName:"Nimvik",courses:
                [{courseID:6,"started":{semester:"Spring",year:2016},passedCredits:15},
                {courseID:24,"started":{semester:"Autumn",year:2019},passedCredits:4},
                {courseID:13,"started":{semester:"Spring",year:2019},passedCredits:12},
                {courseID:14,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:9,"started":{semester:"Spring",year:2016},passedCredits:0},
                {courseID:7,"started":{semester:"Autumn",year:2015},passedCredits:15}]},
        {studentID:8,firstName:"Clara Marie",lastName:"Einarsson",courses:
                [{courseID:20,"started":{semester:"Spring",year:2017},passedCredits:10},
                {courseID:21,"started":{semester:"Spring",year:2016},passedCredits:2},
                {courseID:19,"started":{semester:"Autumn",year:2014},passedCredits:7.5},
                {courseID:5,"started":{semester:"Autumn",year:2015},passedCredits:13},
                {courseID:21,"started":{semester:"Autumn",year:2018},passedCredits:7.5},
                {courseID:7,"started":{semester:"Spring",year:2018},passedCredits:12},
                {courseID:24,"started":{semester:"Autumn",year:2017},passedCredits:12.5},
                {courseID:25,"started":{semester:"Autumn",year:2017},passedCredits:15},
                {courseID:20,"started":{semester:"Spring",year:2017},passedCredits:12.5},
                {courseID:8,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:16,"started":{semester:"Spring",year:2014},passedCredits:1}]},
        {studentID:9,firstName:"Mehmet Kaan",lastName:"Knutsson",courses:
                [{courseID:0,"started":{semester:"Autumn",year:2019},passedCredits:9},
                {courseID:0,"started":{semester:"Spring",year:2016},passedCredits:8},
                {courseID:11,"started":{semester:"Autumn",year:2018},passedCredits:0},
                {courseID:17,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:29,"started":{semester:"Autumn",year:2016},passedCredits:7.5}]},
        {studentID:10,firstName:"Bea",lastName:"Duncalf",courses:
                [{courseID:12,"started":{semester:"Autumn",year:2019},passedCredits:0},
                {courseID:14,"started":{semester:"Spring",year:2016},passedCredits:5},
                {courseID:8,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:21,"started":{semester:"Autumn",year:2017},passedCredits:7.5},
                {courseID:2,"started":{semester:"Autumn",year:2019},passedCredits:0},
                {courseID:11,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:12,"started":{semester:"Spring",year:2018},passedCredits:5},
                {courseID:3,"started":{semester:"Spring",year:2015},passedCredits:7}]},
        {studentID:11,firstName:"Sohny",lastName:"Bröddén",courses:
                [{courseID:13,"started":{semester:"Spring",year:2017},passedCredits:12},
                {courseID:21,"started":{semester:"Spring",year:2014},passedCredits:1},
                {courseID:27,"started":{semester:"Autumn",year:2019},passedCredits:12.5},
                {courseID:24,"started":{semester:"Autumn",year:2019},passedCredits:8},
                {courseID:2,"started":{semester:"Spring",year:2018},passedCredits:5},
                {courseID:17,"started":{semester:"Spring",year:2014},passedCredits:7.5},
                {courseID:29,"started":{semester:"Spring",year:2019},passedCredits:2},
                {courseID:6,"started":{semester:"Spring",year:2019},passedCredits:15},
                {courseID:22,"started":{semester:"Spring",year:2019},passedCredits:9},
                {courseID:13,"started":{semester:"Autumn",year:2015},passedCredits:2},
                {courseID:24,"started":{semester:"Autumn",year:2014},passedCredits:12.5},
                {courseID:21,"started":{semester:"Autumn",year:2014},passedCredits:0}]},
        {studentID:12,firstName:"Ellinor",lastName:"Boukhezzar",courses:
                [{courseID:3,"started":{semester:"Autumn",year:2016},passedCredits:4},
                {courseID:3,"started":{semester:"Autumn",year:2015},passedCredits:2},
                {courseID:12,"started":{semester:"Autumn",year:2016},passedCredits:5},
                {courseID:4,"started":{semester:"Autumn",year:2014},passedCredits:2},
                {courseID:10,"started":{semester:"Spring",year:2018},passedCredits:6},
                {courseID:20,"started":{semester:"Spring",year:2018},passedCredits:12.5}]},
        {studentID:13,firstName:"Matilda",lastName:"Lund",courses:
                [{courseID:0,"started":{semester:"Autumn",year:2017},passedCredits:15},
                {courseID:12,"started":{semester:"Spring",year:2018},passedCredits:5},
                {courseID:17,"started":{semester:"Spring",year:2016},passedCredits:2},
                {courseID:3,"started":{semester:"Autumn",year:2017},passedCredits:7.5},
                {courseID:20,"started":{semester:"Spring",year:2014},passedCredits:2},
                {courseID:19,"started":{semester:"Autumn",year:2015},passedCredits:5}]},
        {studentID:14,firstName:"Wilma",lastName:"Olsson",courses:
                [{courseID:6,"started":{semester:"Spring",year:2015},passedCredits:14},
                {courseID:18,"started":{semester:"Autumn",year:2019},passedCredits:2},
                {courseID:17,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:13,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:16,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:17,"started":{semester:"Spring",year:2018},passedCredits:0},
                {courseID:12,"started":{semester:"Spring",year:2014},passedCredits:3}]},
        {studentID:15,firstName:"Ellinor",lastName:"Stark Jönsson",courses:
                [{courseID:4,"started":{semester:"Spring",year:2019},passedCredits:12.5},
                {courseID:19,"started":{semester:"Autumn",year:2019},passedCredits:2},
                {courseID:21,"started":{semester:"Autumn",year:2019},passedCredits:2},
                {courseID:7,"started":{semester:"Autumn",year:2016},passedCredits:1},
                {courseID:7,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:22,"started":{semester:"Autumn",year:2017},passedCredits:15},
                {courseID:5,"started":{semester:"Autumn",year:2016},passedCredits:4},
                {courseID:12,"started":{semester:"Spring",year:2015},passedCredits:5},
                {courseID:8,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:18,"started":{semester:"Autumn",year:2015},passedCredits:4},
                {courseID:26,"started":{semester:"Autumn",year:2019},passedCredits:0},
                {courseID:15,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:17,"started":{semester:"Spring",year:2017},passedCredits:1}]},
        {studentID:16,firstName:"Bea",lastName:"Sigeback",courses:
                [{courseID:22,"started":{semester:"Autumn",year:2014},passedCredits:15},
                {courseID:10,"started":{semester:"Spring",year:2014},passedCredits:7},
                {courseID:2,"started":{semester:"Spring",year:2015},passedCredits:5},
                {courseID:1,"started":{semester:"Autumn",year:2019},passedCredits:5},
                {courseID:4,"started":{semester:"Autumn",year:2014},passedCredits:8},
                {courseID:17,"started":{semester:"Autumn",year:2019},passedCredits:7.5}]},
        {studentID:17,firstName:"Pranvera",lastName:"Sowole",courses:
                [{courseID:7,"started":{semester:"Spring",year:2017},passedCredits:14},
                {courseID:24,"started":{semester:"Autumn",year:2014},passedCredits:12.5},
                {courseID:10,"started":{semester:"Autumn",year:2019},passedCredits:15},
                {courseID:19,"started":{semester:"Autumn",year:2014},passedCredits:1},
                {courseID:18,"started":{semester:"Autumn",year:2017},passedCredits:3}]},
        {studentID:18,firstName:"Pranvera",lastName:"Knutz",courses:
                [{courseID:20,"started":{semester:"Autumn",year:2014},passedCredits:12.5},
                {courseID:26,"started":{semester:"Autumn",year:2016},passedCredits:7.5},
                {courseID:21,"started":{semester:"Autumn",year:2015},passedCredits:4},
                {courseID:16,"started":{semester:"Spring",year:2016},passedCredits:5},
                {courseID:27,"started":{semester:"Autumn",year:2014},passedCredits:12.5},
                {courseID:12,"started":{semester:"Spring",year:2016},passedCredits:1},
                {courseID:7,"started":{semester:"Spring",year:2017},passedCredits:15},
                {courseID:0,"started":{semester:"Autumn",year:2018},passedCredits:15},
                {courseID:14,"started":{semester:"Autumn",year:2018},passedCredits:2},
                {courseID:14,"started":{semester:"Spring",year:2016},passedCredits:5}]},
        {studentID:19,firstName:"Isak",lastName:"Sowole",courses:
                [{courseID:26,"started":{semester:"Autumn",year:2017},passedCredits:7.5},
                {courseID:9,"started":{semester:"Autumn",year:2014},passedCredits:2},
                {courseID:8,"started":{semester:"Spring",year:2016},passedCredits:0},
                {courseID:28,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:14,"started":{semester:"Spring",year:2014},passedCredits:4},
                {courseID:16,"started":{semester:"Spring",year:2015},passedCredits:5},
                {courseID:1,"started":{semester:"Spring",year:2016},passedCredits:5},
                {courseID:0,"started":{semester:"Autumn",year:2016},passedCredits:15},
                {courseID:26,"started":{semester:"Autumn",year:2014},passedCredits:7.5},
                {courseID:29,"started":{semester:"Spring",year:2016},passedCredits:5},
                {courseID:20,"started":{semester:"Autumn",year:2014},passedCredits:3},
                {courseID:11,"started":{semester:"Autumn",year:2018},passedCredits:2},
                {courseID:9,"started":{semester:"Spring",year:2017},passedCredits:0},
                {courseID:13,"started":{semester:"Autumn",year:2017},passedCredits:10}]},
        {studentID:20,firstName:"Wilma",lastName:"Thanjalak",courses:
                [{courseID:5,"started":{semester:"Spring",year:2017},passedCredits:15},
                {courseID:6,"started":{semester:"Spring",year:2015},passedCredits:15},
                {courseID:15,"started":{semester:"Spring",year:2014},passedCredits:5},
                {courseID:18,"started":{semester:"Autumn",year:2016},passedCredits:0},
                {courseID:6,"started":{semester:"Autumn",year:2018},passedCredits:15},
                {courseID:20,"started":{semester:"Spring",year:2016},passedCredits:1},
                {courseID:24,"started":{semester:"Autumn",year:2016},passedCredits:12.5},
                {courseID:27,"started":{semester:"Autumn",year:2015},passedCredits:6}]},
        {studentID:21,firstName:"Tea",lastName:"Nimvik",courses:
                [{courseID:8,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:15,"started":{semester:"Autumn",year:2017},passedCredits:4},
                {courseID:12,"started":{semester:"Spring",year:2018},passedCredits:2},
                {courseID:27,"started":{semester:"Autumn",year:2019},passedCredits:12.5},
                {courseID:15,"started":{semester:"Spring",year:2014},passedCredits:3},
                {courseID:4,"started":{semester:"Autumn",year:2018},passedCredits:0},
                {courseID:15,"started":{semester:"Autumn",year:2015},passedCredits:4},
                {courseID:15,"started":{semester:"Spring",year:2016},passedCredits:1},
                {courseID:20,"started":{semester:"Spring",year:2014},passedCredits:10},
                {courseID:16,"started":{semester:"Autumn",year:2016},passedCredits:5}]},
        {studentID:22,firstName:"Lina",lastName:"Einarsson",courses:
                [{courseID:12,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:28,"started":{semester:"Spring",year:2017},passedCredits:6},
                {courseID:11,"started":{semester:"Autumn",year:2015},passedCredits:1},
                {courseID:12,"started":{semester:"Spring",year:2019},passedCredits:1},
                {courseID:7,"started":{semester:"Spring",year:2016},passedCredits:14},
                {courseID:24,"started":{semester:"Autumn",year:2016},passedCredits:12.5},
                {courseID:2,"started":{semester:"Spring",year:2014},passedCredits:4},
                {courseID:13,"started":{semester:"Spring",year:2018},passedCredits:10}]},
        {studentID:23,firstName:"Jonna",lastName:"Einarsson",courses:
                [{courseID:28,"started":{semester:"Spring",year:2016},passedCredits:0},
                {courseID:8,"started":{semester:"Spring",year:2016},passedCredits:2},
                {courseID:10,"started":{semester:"Autumn",year:2016},passedCredits:3},
                {courseID:17,"started":{semester:"Spring",year:2015},passedCredits:7.5},
                {courseID:10,"started":{semester:"Spring",year:2016},passedCredits:15},
                {courseID:17,"started":{semester:"Spring",year:2017},passedCredits:3},
                {courseID:21,"started":{semester:"Autumn",year:2016},passedCredits:3}]},
        {studentID:24,firstName:"Lina",lastName:"Pihl",courses:
                [{courseID:20,"started":{semester:"Autumn",year:2018},passedCredits:12.5},
                {courseID:29,"started":{semester:"Autumn",year:2014},passedCredits:7.5},
                {courseID:15,"started":{semester:"Autumn",year:2017},passedCredits:1},
                {courseID:24,"started":{semester:"Spring",year:2016},passedCredits:1},
                {courseID:19,"started":{semester:"Autumn",year:2016},passedCredits:7.5},
                {courseID:24,"started":{semester:"Spring",year:2014},passedCredits:12.5},
                {courseID:19,"started":{semester:"Spring",year:2015},passedCredits:7.5},
                {courseID:1,"started":{semester:"Autumn",year:2015},passedCredits:5},
                {courseID:20,"started":{semester:"Autumn",year:2014},passedCredits:11},
                {courseID:1,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:7,"started":{semester:"Autumn",year:2016},passedCredits:14},
                {courseID:14,"started":{semester:"Autumn",year:2016},passedCredits:5}]},
        {studentID:25,firstName:"Elin",lastName:"Wulkan",courses:
                [{courseID:18,"started":{semester:"Spring",year:2019},passedCredits:3},
                {courseID:24,"started":{semester:"Spring",year:2017},passedCredits:2},
                {courseID:13,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:4,"started":{semester:"Autumn",year:2015},passedCredits:9},
                {courseID:27,"started":{semester:"Spring",year:2019},passedCredits:3},
                {courseID:20,"started":{semester:"Autumn",year:2016},passedCredits:7},
                {courseID:24,"started":{semester:"Autumn",year:2018},passedCredits:12.5},
                {courseID:4,"started":{semester:"Spring",year:2016},passedCredits:3}]},
        {studentID:26,firstName:"Niklas",lastName:"Gerre",courses:
                [{courseID:20,"started":{semester:"Spring",year:2017},passedCredits:2},
                {courseID:0,"started":{semester:"Autumn",year:2014},passedCredits:11},
                {courseID:14,"started":{semester:"Spring",year:2015},passedCredits:1},
                {courseID:5,"started":{semester:"Autumn",year:2019},passedCredits:15},
                {courseID:22,"started":{semester:"Autumn",year:2019},passedCredits:15},
                {courseID:23,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:11,"started":{semester:"Spring",year:2014},passedCredits:5},
                {courseID:12,"started":{semester:"Autumn",year:2015},passedCredits:5}]},
        {studentID:27,firstName:"Niklas",lastName:"Knutsson",courses:
                [{courseID:21,"started":{semester:"Autumn",year:2018},passedCredits:7.5},
                {courseID:16,"started":{semester:"Autumn",year:2019},passedCredits:5},
                {courseID:2,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:26,"started":{semester:"Autumn",year:2015},passedCredits:7.5},
                {courseID:12,"started":{semester:"Spring",year:2017},passedCredits:0},
                {courseID:4,"started":{semester:"Autumn",year:2014},passedCredits:12.5},
                {courseID:24,"started":{semester:"Spring",year:2019},passedCredits:8},
                {courseID:11,"started":{semester:"Spring",year:2016},passedCredits:3},
                {courseID:13,"started":{semester:"Autumn",year:2018},passedCredits:15},
                {courseID:23,"started":{semester:"Autumn",year:2014},passedCredits:4},
                {courseID:8,"started":{semester:"Spring",year:2018},passedCredits:5},
                {courseID:15,"started":{semester:"Spring",year:2018},passedCredits:1},
                {courseID:5,"started":{semester:"Spring",year:2014},passedCredits:15},
                {courseID:11,"started":{semester:"Spring",year:2017},passedCredits:5}]},
        {studentID:28,firstName:"Edit",lastName:"Lund",courses:
                [{courseID:5,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:16,"started":{semester:"Spring",year:2014},passedCredits:5},
                {courseID:24,"started":{semester:"Autumn",year:2018},passedCredits:12.5},
                {courseID:5,"started":{semester:"Spring",year:2015},passedCredits:15},
                {courseID:1,"started":{semester:"Spring",year:2018},passedCredits:3},
                {courseID:0,"started":{semester:"Spring",year:2015},passedCredits:15},
                {courseID:29,"started":{semester:"Autumn",year:2015},passedCredits:7.5},
                {courseID:28,"started":{semester:"Autumn",year:2019},passedCredits:7.5},
                {courseID:24,"started":{semester:"Spring",year:2019},passedCredits:12.5}]},
        {studentID:29,firstName:"Elsa",lastName:"Wulkan",courses:
                [{courseID:4,"started":{semester:"Autumn",year:2019},passedCredits:12.5},
                {courseID:5,"started":{semester:"Autumn",year:2016},passedCredits:15},
                {courseID:4,"started":{semester:"Spring",year:2019},passedCredits:0},
                {courseID:24,"started":{semester:"Spring",year:2015},passedCredits:12.5},
                {courseID:3,"started":{semester:"Autumn",year:2018},passedCredits:7.5},
                {courseID:0,"started":{semester:"Spring",year:2016},passedCredits:15},
                {courseID:16,"started":{semester:"Spring",year:2014},passedCredits:1},
                {courseID:28,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:2,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:4,"started":{semester:"Spring",year:2014},passedCredits:6},
                {courseID:5,"started":{semester:"Spring",year:2018},passedCredits:15},
                {courseID:22,"started":{semester:"Autumn",year:2015},passedCredits:15}]},
        {studentID:30,firstName:"Lina",lastName:"Stavnjak",courses:
                [{courseID:18,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:3,"started":{semester:"Spring",year:2014},passedCredits:7.5},
                {courseID:15,"started":{semester:"Autumn",year:2018},passedCredits:3},
                {courseID:14,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:23,"started":{semester:"Autumn",year:2016},passedCredits:5},
                {courseID:24,"started":{semester:"Spring",year:2019},passedCredits:12.5},
                {courseID:10,"started":{semester:"Spring",year:2016},passedCredits:6},
                {courseID:19,"started":{semester:"Spring",year:2018},passedCredits:7.5},
                {courseID:27,"started":{semester:"Spring",year:2018},passedCredits:12.5}]},
        {studentID:31,firstName:"Malin",lastName:"Gistorp Larsson",courses:
                [{courseID:20,"started":{semester:"Autumn",year:2018},passedCredits:9},
                {courseID:23,"started":{semester:"Autumn",year:2015},passedCredits:2},
                {courseID:3,"started":{semester:"Spring",year:2019},passedCredits:6},
                {courseID:14,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:0,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:26,"started":{semester:"Spring",year:2016},passedCredits:7},
                {courseID:23,"started":{semester:"Autumn",year:2018},passedCredits:5},
                {courseID:23,"started":{semester:"Autumn",year:2014},passedCredits:2},
                {courseID:23,"started":{semester:"Autumn",year:2015},passedCredits:2},
                {courseID:0,"started":{semester:"Spring",year:2016},passedCredits:15},
                {courseID:10,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:5,"started":{semester:"Spring",year:2019},passedCredits:15},
                {courseID:2,"started":{semester:"Spring",year:2015},passedCredits:4},
                {courseID:28,"started":{semester:"Spring",year:2015},passedCredits:6}]},
        {studentID:32,firstName:"Ivan",lastName:"Pihl",courses:
                [{courseID:16,"started":{semester:"Autumn",year:2018},passedCredits:0},
                {courseID:1,"started":{semester:"Autumn",year:2017},passedCredits:5},
                {courseID:10,"started":{semester:"Spring",year:2019},passedCredits:13},
                {courseID:2,"started":{semester:"Autumn",year:2019},passedCredits:0},
                {courseID:14,"started":{semester:"Autumn",year:2016},passedCredits:2},
                {courseID:24,"started":{semester:"Autumn",year:2016},passedCredits:12.5},
                {courseID:14,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:9,"started":{semester:"Spring",year:2016},passedCredits:1},
                {courseID:28,"started":{semester:"Autumn",year:2014},passedCredits:7},
                {courseID:15,"started":{semester:"Autumn",year:2019},passedCredits:3},
                {courseID:1,"started":{semester:"Spring",year:2016},passedCredits:5}]},
        {studentID:33,firstName:"Matilda",lastName:"Stark Jönsson",courses:
                [{courseID:16,"started":{semester:"Autumn",year:2014},passedCredits:4},
                {courseID:25,"started":{semester:"Autumn",year:2019},passedCredits:15},
                {courseID:3,"started":{semester:"Spring",year:2017},passedCredits:7.5},
                {courseID:22,"started":{semester:"Autumn",year:2014},passedCredits:15},
                {courseID:5,"started":{semester:"Autumn",year:2015},passedCredits:9},
                {courseID:28,"started":{semester:"Autumn",year:2015},passedCredits:7.5},
                {courseID:8,"started":{semester:"Autumn",year:2014},passedCredits:0},
                {courseID:26,"started":{semester:"Spring",year:2014},passedCredits:7.5},
                {courseID:20,"started":{semester:"Spring",year:2018},passedCredits:12.5},
                {courseID:0,"started":{semester:"Autumn",year:2015},passedCredits:15},
                {courseID:15,"started":{semester:"Autumn",year:2015},passedCredits:4},
                {courseID:9,"started":{semester:"Spring",year:2015},passedCredits:2},
                {courseID:26,"started":{semester:"Spring",year:2016},passedCredits:7.5}]},
        {studentID:34,firstName:"Alexander",lastName:"Gistorp Larsson",courses:
                [{courseID:27,"started":{semester:"Spring",year:2014},passedCredits:12.5},
                {courseID:21,"started":{semester:"Spring",year:2016},passedCredits:1},
                {courseID:5,"started":{semester:"Autumn",year:2016},passedCredits:15},
                {courseID:3,"started":{semester:"Spring",year:2016},passedCredits:2},
                {courseID:25,"started":{semester:"Spring",year:2016},passedCredits:15},
                {courseID:6,"started":{semester:"Spring",year:2014},passedCredits:13},
                {courseID:8,"started":{semester:"Autumn",year:2019},passedCredits:5},
                {courseID:25,"started":{semester:"Autumn",year:2018},passedCredits:15},
                {courseID:23,"started":{semester:"Autumn",year:2015},passedCredits:4},
                {courseID:22,"started":{semester:"Spring",year:2015},passedCredits:4},
                {courseID:15,"started":{semester:"Spring",year:2019},passedCredits:1},
                {courseID:8,"started":{semester:"Spring",year:2017},passedCredits:2}]},
        {studentID:35,firstName:"Elin",lastName:"Tran",courses:
                [{courseID:27,"started":{semester:"Autumn",year:2019},passedCredits:12.5},
                {courseID:12,"started":{semester:"Autumn",year:2016},passedCredits:5},
                {courseID:28,"started":{semester:"Spring",year:2016},passedCredits:0},
                {courseID:27,"started":{semester:"Spring",year:2019},passedCredits:8},
                {courseID:2,"started":{semester:"Spring",year:2019},passedCredits:3},
                {courseID:4,"started":{semester:"Spring",year:2019},passedCredits:2},
                {courseID:26,"started":{semester:"Autumn",year:2015},passedCredits:5},
                {courseID:6,"started":{semester:"Autumn",year:2015},passedCredits:9},
                {courseID:2,"started":{semester:"Spring",year:2014},passedCredits:2},
                {courseID:8,"started":{semester:"Spring",year:2017},passedCredits:2},
                {courseID:8,"started":{semester:"Spring",year:2018},passedCredits:5},
                {courseID:19,"started":{semester:"Autumn",year:2016},passedCredits:7.5},
                {courseID:22,"started":{semester:"Autumn",year:2017},passedCredits:15}]},
        {studentID:36,firstName:"Kim",lastName:"Tran",courses:
                [{courseID:20,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:26,"started":{semester:"Spring",year:2014},passedCredits:3},
                {courseID:24,"started":{semester:"Spring",year:2018},passedCredits:12.5},
                {courseID:16,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:28,"started":{semester:"Spring",year:2018},passedCredits:7},
                {courseID:2,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:12,"started":{semester:"Autumn",year:2018},passedCredits:5}]},
        {studentID:37,firstName:"Melinda",lastName:"Taspunar",courses:
                [{courseID:8,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:15,"started":{semester:"Spring",year:2015},passedCredits:1},
                {courseID:25,"started":{semester:"Autumn",year:2018},passedCredits:15},
                {courseID:26,"started":{semester:"Spring",year:2019},passedCredits:6},
                {courseID:14,"started":{semester:"Spring",year:2019},passedCredits:5}]},
        {studentID:38,firstName:"Sally",lastName:"Tran",courses:
                [{courseID:25,"started":{semester:"Autumn",year:2015},passedCredits:3},
                {courseID:23,"started":{semester:"Spring",year:2015},passedCredits:1},
                {courseID:1,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:8,"started":{semester:"Spring",year:2017},passedCredits:5},
                {courseID:6,"started":{semester:"Spring",year:2017},passedCredits:5}]},
        {studentID:39,firstName:"Wilma",lastName:"Coursell",courses:
                [{courseID:1,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:28,"started":{semester:"Spring",year:2015},passedCredits:7.5},
                {courseID:2,"started":{semester:"Spring",year:2018},passedCredits:1},
                {courseID:19,"started":{semester:"Autumn",year:2017},passedCredits:7.5},
                {courseID:24,"started":{semester:"Spring",year:2014},passedCredits:12.5},
                {courseID:25,"started":{semester:"Spring",year:2019},passedCredits:5},
                {courseID:20,"started":{semester:"Autumn",year:2018},passedCredits:12.5},
                {courseID:26,"started":{semester:"Spring",year:2016},passedCredits:0},
                {courseID:29,"started":{semester:"Spring",year:2016},passedCredits:7.5},
                {courseID:24,"started":{semester:"Spring",year:2015},passedCredits:8},
                {courseID:1,"started":{semester:"Autumn",year:2014},passedCredits:5},
                {courseID:19,"started":{semester:"Autumn",year:2019},passedCredits:1},
                {courseID:8,"started":{semester:"Spring",year:2015},passedCredits:5}]}
];
const COURSES = [
    {
        courseID:0,
        title:"Literature of Contemporary Western Civilization",
        totalCredits:15,
        teachers:[0,5],
        courseResponsible:0
    },
    {courseID:1,title:"Architecture of Persia",totalCredits:5,teachers:[5,0],courseResponsible:5},
    {courseID:2,title:"Literature of the Romantic Age",totalCredits:5,teachers:[1,6,7],courseResponsible:1},
    {courseID:3,title:"Architecture of the Rennaisance Age",totalCredits:7.5,teachers:[2],courseResponsible:2},
    {courseID:4,title:"History of Contemporary Western Civilization",totalCredits:12.5,teachers:[8],courseResponsible:8},
    {courseID:5,title:"Poetry of Persia",totalCredits:15,teachers:[8,7],courseResponsible:8},
    {courseID:6,title:"Architecture of Contemporary Western Civilization",totalCredits:15,teachers:[6,2],courseResponsible:6},
    {courseID:7,title:"Poetry of the Incan Empire",totalCredits:15,teachers:[3,7,1],courseResponsible:3},
    {courseID:8,title:"History of the Baroque Age",totalCredits:5,teachers:[9,3,0],courseResponsible:9},
    {courseID:9,title:"Poetry of North and South America",totalCredits:5,teachers:[6],courseResponsible:6},
    {courseID:10,title:"Architecture of the Romantic Age",totalCredits:15,teachers:[6,8,2],courseResponsible:6},
    {courseID:11,title:"Literature of the Middle Ages",totalCredits:5,teachers:[8,2,1],courseResponsible:8},
    {courseID:12,title:"Literature of North and South America",totalCredits:5,teachers:[0,5,8],courseResponsible:0},
    {courseID:13,title:"Literature of the Baroque Age",totalCredits:15,teachers:[4,0],courseResponsible:4},
    {courseID:14,title:"Architecture of Rome",totalCredits:5,teachers:[5],courseResponsible:5},
    {courseID:15,title:"Art of Rome",totalCredits:5,teachers:[3,8],courseResponsible:3},
    {courseID:16,title:"Art of the Romantic Age",totalCredits:5,teachers:[3],courseResponsible:3},
    {courseID:17,title:"Art of Contemporary Western Civilization",totalCredits:7.5,teachers:[2,0,3],courseResponsible:2},
    {courseID:18,title:"History of Persia",totalCredits:5,teachers:[1],courseResponsible:1},
    {courseID:19,title:"History of the Incan Empire",totalCredits:7.5,teachers:[5],courseResponsible:5},
    {courseID:20,title:"History of Rome",totalCredits:12.5,teachers:[5,7],courseResponsible:5},
    {courseID:21,title:"Architecture of the Middle Ages",totalCredits:7.5,teachers:[3,7,5],courseResponsible:3},
    {courseID:22,title:"Art of Classic Greece",totalCredits:15,teachers:[1],courseResponsible:1},
    {courseID:23,title:"History of the Middle Ages",totalCredits:5,teachers:[5],courseResponsible:5},
    {courseID:24,title:"Literature of Classic Greece",totalCredits:12.5,teachers:[1],courseResponsible:1},
    {courseID:25,title:"Poetry of the Baroque Age",totalCredits:15,teachers:[0,8,2],courseResponsible:0},
    {courseID:26,title:"Architecture of Classic Greece",totalCredits:7.5,teachers:[7,3,5],courseResponsible:7},
    {courseID:27,title:"Literature of the Incan Empire",totalCredits:12.5,teachers:[3,2],courseResponsible:3},
    {courseID:28,title:"Poetry of the Middle Ages",totalCredits:7.5,teachers:[3,0],courseResponsible:3},
    {courseID:29,title:"History of the Romantic Age",totalCredits:7.5,teachers:[7,5],courseResponsible:7}
];
const TEACHERS = [
    {
        teacherID: 0,
        firstName: "Sebastian",
        lastName: "Pineiro",
        post: "Lektor"
    },
    {
        teacherID: 1,
        firstName: "Erik",
        lastName: "Karlsson",
        post: "Adjunkt"
    },
    {
        teacherID: 2,
        firstName: "Sebastian",
        lastName: "Boztepe",
        post: "Docent"
    },
    {
        teacherID: 3,
        firstName: "Maria",
        lastName: "Berg",
        post: "Professor"
    },
    {
        teacherID: 4,
        firstName: "Suzan",
        lastName: "Engberg",
        post: "Docent"
    },
    {
        teacherID: 5,
        firstName: "Sven",
        lastName: "Bengtegård",
        post: "Lektor"
    },
    {
        teacherID: 6,
        firstName: "Johannes",
        lastName: "Packmohr",
        post: "Lektor"
    },
    {
        teacherID: 7,
        firstName: "Carina",
        lastName: "Corominas",
        post: "Lektor"
    },
    {
        teacherID: 8,
        firstName: "Thomas",
        lastName: "Jakobsson",
        post: "Adjunkt"
    },
    {
        teacherID: 9,
        firstName: "Pär",
        lastName: "Ström Hyllén",
        post: "Adjunkt"
    },
];




